---
version: "2"
volumes:
  bookstack-config: {}
  haproxy-certs: {}
services:
  haproxy-lb:
    image: "haproxy:2.3"
    volumes:
      - haproxy-certs:/certs
      - /home/docker-admin/code/automation/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 80:80
      - 443:443
    command:
      haproxy -c -f /usr/local/etc/haproxy/haproxy.cfg
  bookstack:
    image: ghcr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://books.szyjka.net
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=Allah123
      - DB_DATABASE=bookstackapp
    ports:
      - 7820:80
    volumes:
      - bookstack-config:/config
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: ghcr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=Allah123
      - TZ=USA/NewYork
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=Allah123
    volumes:
      - /bookstackdb-config:/config
    restart: unless-stopped
